version: '3'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
