version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: usuario_postgres
      POSTGRES_PASSWORD: contraseña_postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: miltonho@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: .PARpga2023.
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    links:
      - postgres:postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:


